# app info
appInfo:
  name: "Golang DIP Error Code REST API - local"
  description: "DIP Error Code Lookup"
  env: "LOCAL"
  version: "1.0.0"
  gitCommit: ${GIT_COMMIT}

database:
  postgres:
    driver: postgres
    host: dip-rds-instance-1.cwbtknhxbnob.us-west-1.rds.amazonaws.com
    port: 5432
    dbname: icode
    username: night_koder
    password: koder!@#
    dsn: "user=night_koder password=koder!@# host=dip-rds-instance-1.cwbtknhxbnob.us-west-1.rds.amazonaws.com port=5432 dbname=icode sslmode=disable"
  maxIdleConns: 0
  maxOpenConns: 5
  maxIdleTime: 60
